[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "config-as-json"
version = "0.8"
authors = [
  { name="Tom Björkholm", email="klausuler_linnet0q@icloud.com" },
]
description = "Read, write, validate, and migrate JSON-backed config classes."
readme = "README_pypi.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE.txt"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dynamic = ["dependencies"]

[project.urls]
"Source code" = "https://bitbucket.org/tom-bjorkholm/config_as_json/"

